<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DemonCodex.Rules/DemonCodex.Rules.csproj" />
    <Compile Include="../DemonCodex.Unity/Assets/DemonCodex/LocalMatch/*.cs" />
  </ItemGroup>
</Project>
