<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../game/DemonCodex.LocalMatch/DemonCodex.LocalMatch.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <Compile Include="../../game/DemonCodex.Unity/Assets/DemonCodex/Tests/LocalMatch/*.cs" />
    <Compile Include="../../game/DemonCodex.Unity/Assets/DemonCodex/Development/*.cs" />
  </ItemGroup>
</Project>
